version: 2.1
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.6
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            touch ~/.aws/credentials
            chmod 600 ~/.aws/config
            chmod 600 ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "awsebcli install complete"
      - run:
          name: Deploying
          command: eb deploy
 
workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master