version: 2.1
orbs:
  awsebcli: sbc-orbs/awsebcli@0.0.3
jobs:
  deploy:
    executor: awsebcli
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: Deploying
          command: eb deploy issues-prod-env

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
